language: go

sudo: false

go:
- 1.7

install:
  - go get -d -t -v ./...
  - go build ./...

script:
- go test -race -covermode=atomic -coverprofile=currentbehaviour.txt ./current/behaviour
- cat currentbehaviour.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currentclgtree.txt ./current/clg/tree
- cat currentclgtree.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currentdestination.txt ./current/destination
- cat currentdestination.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currentexpectation.txt ./current/expectation
- cat currentexpectation.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currentsession.txt ./current/session
- cat currentsession.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currentsource.txt ./current/source
- cat currentsource.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=currenttrial.txt ./current/trial
- cat currenttrial.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=firstbehaviour.txt ./first/behaviour
- cat firstbehaviour.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=firstinformation.txt ./first/information
- cat firstinformation.txt >> coverage.txt

notifications:
  email: false

branches:
  only:
    - master

after_success:
- bash <(curl -s https://codecov.io/bash)
